spring.application.name=wiremock-frontend
server.port=${PORT:8782}
spring.thymeleaf.cache=false
wiremock.base-url=${WIREMOCK_BASE_URL:http://wiremock:8080}
wiremock.connect-timeout=${WIREMOCK_CONNECT_TIMEOUT:2s}
wiremock.read-timeout=${WIREMOCK_READ_TIMEOUT:5s}
